module.exports = {
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/**/*.{js,ts}',
    '!<rootDir>/src/main.ts',
    '!<rootDir>/test/*',
    '!<rootDir>/**/swagger/*',
    '!<rootDir>/src/common/decorators/**/*',
    '!<rootDir>/src/common/errors/**/*',
    '!<rootDir>/src/common/interfaces/**/*',
    '!<rootDir>/src/config/**/*',
    '!<rootDir>/src/constants/**/*',
    '!<rootDir>/src/**/__fixtures__/**/*',
    '!<rootDir>/src/**/*.spec.ts',
    '!<rootDir>/src/**/*.e2e-spec.ts',
    '!<rootDir>/src/**/*.module.ts',
    '!<rootDir>/src/**/dtos/**',
  ],
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: [
    '<rootDir>/src/(sdk|swagger|schema|__fixtures__)/',
  ],
  coverageReporters: ['html', 'lcov', 'text', 'text-summary'],
  moduleFileExtensions: ['js', 'json', 'ts'],
  roots: ['<rootDir>/src'],
  setupFiles: ['<rootDir>/jest-files/setup.ts'],
  setupFilesAfterEnv: ['<rootDir>/jest-files/__fixtures__/mock-logger.ts'],
  testEnvironment: 'node',
  testMatch: ['<rootDir>/src/**/*.spec.ts'],
  testPathIgnorePatterns: ['dist'],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
};
