export enum HAIR_SERVICE_INGREDIENT_BRAND_LENGHT {
  MAX = 50,
  MIN = 2,
}

export enum HAIR_SERVICE_INGREDIENT_HEIGHT {
  MAX = 10,
  MIN = 0,
}

export enum HAIR_SERVICE_INGREDIENT_OXIDIZING {
  MAX = 100,
  MIN = 0,
}

export enum HAIR_SERVICE_INGREDIENT_QUANTITY_LENGHT {
  MAX = 10,
  MIN = 1,
}

export enum HAIR_SERVICE_INGREDIENT_TONE_LENGHT {
  MAX = 30,
  MIN = 1,
}

export const HAIR_SERVICE_INGREDIENT_HEIGHT_MAX_DECIMAL_PLACES = 0;
export const HAIR_SERVICE_INGREDIENT_OXIDIZING_MAX_DECIMAL_PLACES = 2;
