export enum HAIR_SERVICE_INGREDIENT_BRAND_LENGTH {
  MAX = 50,
  MIN = 2,
}

export enum HAIR_SERVICE_INGREDIENT_QUANTITY_LENGTH {
  MAX = 10,
  MIN = 1,
}

export enum HAIR_SERVICE_INGREDIENT_TONE_LENGTH {
  MAX = 30,
  MIN = 1,
}
